### ISSUE TITLE
Running locally

### ISSUE THREAD

**Issue by Pusherman2** [Augustin999/SSX999_HEDGE#3]
Hi Augustin,

Very awesome project you have made! 

I am however wondering if it would be possible to run this locally without Gcloud?

I see some references to local environments however I am unsure how what to modify to make it run locally.

Could you please provide some instructions on what to modify to make it run locally and how to import/use the API keys for use by the project?

Thank you and kind regards,

Pusherman

**Comment by Maxxsive** [comment]
Hello! I've got trading idea, it looks like on yours. But I'm not a coder. If you got some intersting, I'll share it with you and we create bot together?
